import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parse } from "yaml";
import { DateTime } from "luxon";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const seedFile = process.env.SEED_YAML ?? "data/wc26.yml";
const doc = parse(readFileSync(join(root, seedFile), "utf8"));

const now = "datetime('now')";
const lines = [
  `-- Generated by scripts/build-seed.mjs from ${seedFile}`,
  "PRAGMA foreign_keys = ON;",
  "BEGIN TRANSACTION;",
];

const tournamentCode = doc.tournament?.code ?? "WC26";
lines.push(
  `INSERT INTO tournaments (id, code, active, created_at, updated_at) VALUES (1, '${tournamentCode}', 1, ${now}, ${now});`
);

let phaseId = 0;
const phaseCodeToId = {};
for (const p of doc.phases) {
  phaseId++;
  phaseCodeToId[p.code] = phaseId;
  const active = p.active ? 1 : 0;
  lines.push(
    `INSERT INTO phases (id, code, level, small_points, big_points, active, tournament_id, created_at, updated_at) VALUES (${phaseId}, '${p.code}', ${p.level}, ${p.small_points}, ${p.big_points}, ${active}, 1, ${now}, ${now});`
  );
}

let teamId = 0;
const teamCodeToId = {};
for (const t of doc.teams) {
  teamId++;
  teamCodeToId[t.code] = teamId;
  lines.push(
    `INSERT INTO teams (id, code, "group", tournament_id, created_at, updated_at) VALUES (${teamId}, '${t.code}', '${t.group}', 1, ${now}, ${now});`
  );
}

function parseMatchDate(str) {
  if (/^\d{4}-\d{2}-\d{2}T/.test(str)) {
    const dt = DateTime.fromISO(str, { zone: "utc" });
    if (!dt.isValid) throw new Error(`Bad ISO date: ${str} ${dt.invalidReason}`);
    return dt.toISO({ suppressMilliseconds: true });
  }
  const s = str.replace(/ CST$/, "");
  const dt = DateTime.fromFormat(s, "yyyy-MM-dd HH:mm", { zone: "America/Chicago" });
  if (!dt.isValid) throw new Error(`Bad date: ${str} ${dt.invalidReason}`);
  return dt.toUTC().toISO({ suppressMilliseconds: true });
}

let matchNum = 0;
for (const m of doc.matches) {
  matchNum++;
  const iso = parseMatchDate(m.date);
  const phase_id = phaseCodeToId[m.phase];
  const esc = (x) => (x == null ? "NULL" : `'${String(x).replace(/'/g, "''")}'`);
  let t1 = "NULL",
    t2 = "NULL",
    l1 = "NULL",
    l2 = "NULL";
  if (m.team1) t1 = teamCodeToId[m.team1];
  if (m.team2) t2 = teamCodeToId[m.team2];
  if (m.team1_label) l1 = esc(m.team1_label);
  if (m.team2_label) l2 = esc(m.team2_label);
  lines.push(
    `INSERT INTO matches (id, number, date, phase_id, team1_id, team2_id, team1_score, team2_score, team1_label, team2_label, ready, tournament_id, is_closed, created_at, updated_at) VALUES (${matchNum}, ${matchNum}, '${iso}', ${phase_id}, ${t1}, ${t2}, NULL, NULL, ${l1}, ${l2}, 0, 1, 0, ${now}, ${now});`
  );
}

lines.push("COMMIT;");

const out = join(root, "migrations/0002_seed.sql");
const seedSql = lines.join("\n") + "\n";
writeFileSync(out, seedSql, "utf8");
console.log("Wrote", out, `(${tournamentCode}, ${matchNum} matches)`);

/** Upgrade path: D1 does not re-run 0002 after it was already applied with CA24. */
const reseed = [
  "-- Auto-generated by scripts/build-seed.mjs — same inserts as 0002_seed.sql after clearing tournament id=1.",
  "-- Apply with: npm run db:migrate:local (or :remote). Destroys prediction_sets tied to tournament 1.",
  "PRAGMA foreign_keys = ON;",
  "BEGIN TRANSACTION;",
  "DELETE FROM tournaments WHERE id = 1;",
  ...lines.slice(3, -1),
  "COMMIT;",
].join("\n");
const outReseed = join(root, "migrations/0003_wc26_reseed.sql");
writeFileSync(outReseed, reseed + "\n", "utf8");
console.log("Wrote", outReseed);
